# run tests using make test
name: Run tests

on:
  push:
    branches:
      - main
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc
      - name: Build
        run: make 
      - name: Run tests
        run: make test_all