name: Benchmark Suite

on:
  push:
    branches:
      - main

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc
      - name: Run benchmark suite
        run: make benchmark
